/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.zensar.gradle;

public class App {

    public String getGreeting() {

        return "Hello world.";
    
    }


    public static void main(String[] args) {

        System.out.println(new App().getGreeting());
    
    }

}


http://www.springframework.org/schema/context


<dependency>
     <groupId>org.springframework</groupId>
     <artifactId>spring-context</artifactId>
     <version>5.1.8.RELEASE</version>
    </dependency>
    
    <dependency>
    <groupId>org.springframework</groupId>
    <artifactId>spring-jdbc</artifactId>
    <version>5.1.8.RELEASE</version>
	</dependency>
	
	<dependency>
    <groupId>mysql</groupId>
    <artifactId>mysql-connector-java</artifactId>
    <version>8.0.16</version>
</dependency>

http://www.springframework.org/schema/mvc
http://www.springframework.org/schema/context